// Lockstep locks for the full-text search grammar: these vectors MIRROR the
// Rust tests (corpus.rs search_match_* / sort_hits) — a drift here means the
// browser twin ranks/frames a hit differently than the shell.

import { describe, expect, test } from "bun:test";

import type { SearchHit } from "../types";
import { queryTokens, searchMatch, sortHits, stripHtmlComments } from "./search";

const hit = (over: Partial<SearchHit>): SearchHit => ({
  id: "a",
  title: "t",
  snippet: "",
  folderId: "Inbox",
  kind: "note",
  rank: 1,
  matchStart: 0,
  matchLen: 1,
  spans: [[0, 1]],
  updatedAt: 0,
  ...over,
});

describe("searchMatch — title > body ranking with char offsets (mirrors Rust)", () => {
  test("ranks a title hit 0, offsets index the TITLE, stored snippet rides through", () => {
    const m = searchMatch("groc", "Groceries", "# Groceries\n\nOlive oil.\n", "Olive oil.");
    expect(m).toEqual({ rank: 0, snippet: "Olive oil.", matchStart: 0, matchLen: 4, spans: [[0, 4]] });
  });

  test("ranks a body hit 2 and frames the match inside the returned snippet", () => {
    const m = searchMatch(
      "sourdough",
      "Groceries",
      "# Groceries\n\nOlive oil, sourdough, butter.\n",
      "Olive oil, sourdough, butter.",
    );
    expect(m?.rank).toBe(2);
    expect(m?.spans).toEqual([[m!.matchStart, m!.matchLen]]);
    const chars = [...(m?.snippet ?? "")];
    expect(chars.slice(m!.matchStart, m!.matchStart + m!.matchLen).join("")).toBe("sourdough");
  });

  test("matches case-insensitively both directions; no match / blank query → null", () => {
    expect(searchMatch("OLIVE", "Groceries", "olive oil", "")).not.toBeNull();
    expect(searchMatch("olive", "Groceries", "OLIVE OIL", "")).not.toBeNull();
    expect(searchMatch("zebra", "Groceries", "olive oil", "")).toBeNull();
    expect(searchMatch("   ", "Groceries", "olive oil", "")).toBeNull();
  });

  test("clips a deep body match to ±60 chars with … on both edges (Rust vector)", () => {
    const long = "a".repeat(100) + "NEEDLE" + "b".repeat(100);
    const m = searchMatch("needle", "T", long, "");
    expect(m?.snippet.startsWith("…")).toBe(true);
    expect(m?.snippet.endsWith("…")).toBe(true);
    const chars = [...(m?.snippet ?? "")];
    expect(chars.slice(m!.matchStart, m!.matchStart + m!.matchLen).join("")).toBe("NEEDLE");
    expect(chars).toHaveLength(1 + 60 + 6 + 60 + 1);
  });

  test("strips emphasis OUTSIDE the match and flattens newlines — offsets stay true", () => {
    const m = searchMatch("needle", "T", "**bold**\nneedle `x`", "");
    const chars = [...(m?.snippet ?? "")];
    expect(chars.slice(m!.matchStart, m!.matchStart + m!.matchLen).join("")).toBe("needle");
    expect(m?.snippet).not.toContain("*");
    expect(m?.snippet).not.toContain("`");
    expect(m?.snippet).not.toContain("\n");
  });

  test("offsets are code points, not UTF-16 units (astral chars before the match)", () => {
    const m = searchMatch("needle", "T", "😀😀 needle", "");
    const chars = [...(m?.snippet ?? "")];
    expect(chars.slice(m!.matchStart, m!.matchStart + m!.matchLen).join("")).toBe("needle");
  });
});

describe("word matching — every query word, any order (mirrors Rust)", () => {
  const framed = (text: string, spans: [number, number][]) =>
    spans.map(([s, l]) => [...text].slice(s, s + l).join(""));

  test("every word in the title ranks 1 with a span per word", () => {
    const m = searchMatch("checklist launch", "Launch checklist", "body", "snip");
    expect(m?.rank).toBe(1);
    expect(framed("Launch checklist", m!.spans)).toEqual(["Launch", "checklist"]);
    expect([m!.matchStart, m!.matchLen]).toEqual([0, 6]);
    expect(m?.snippet).toBe("snip");
    // punctuation and unicode hyphens in the title no longer hide it
    const title = "Gateway Local\u2011to\u2011Production";
    const g = searchMatch("gateway local-to-pr", title, "", "");
    expect(g?.rank).toBe(1);
    expect(framed(title, g!.spans)).toEqual(["Gateway", "Local", "to", "Pr"]);
    expect(searchMatch("launch rocket", "Launch checklist", "", "")).toBeNull();
  });

  test("every word in the body ranks 3 and lights each word inside the window", () => {
    const body = "Notes on the gateway.\n\nThe local run of the **production** cut-over went fine.";
    const m = searchMatch("production gateway", "T", body, "");
    expect(m?.rank).toBe(3);
    expect(framed(m!.snippet, m!.spans)).toEqual(["gateway", "production"]);
    expect(m?.snippet).not.toContain("*");
    expect(m?.matchLen).toBe(7);
  });

  test("tokens dedupe and HTML comments vanish from snippets", () => {
    expect(queryTokens("Local-to-Pr LOCAL, to")).toEqual(["local", "to", "pr"]);
    expect(stripHtmlComments("# reference <!-- Generated by the rotli Filer --> | Note |")).toBe(
      "# reference  | Note |",
    );
    expect(stripHtmlComments("a <!-- open")).toBe("a ");
  });
});

describe("sortHits — rank asc, then recency desc, then id (mirrors Rust sort_hits)", () => {
  test("puts title hits first, then word hits, newest first inside a rank", () => {
    const sorted = sortHits([
      hit({ id: "old-body", rank: 2, updatedAt: 10 }),
      hit({ id: "new-body", rank: 2, updatedAt: 20 }),
      hit({ id: "words", rank: 1, updatedAt: 0 }),
      hit({ id: "title", rank: 0, updatedAt: 1 }),
    ]);
    expect(sorted.map((h) => h.id)).toEqual(["title", "words", "new-body", "old-body"]);
  });
});
