/** The Markdown renderer's explicit storage scheme. A corpus path is not a
 * note-relative path: shortening it to a basename makes the editor look at the
 * vault root and produces a broken image. */
export function markdownImageSource(corpusRelativePath: string): string {
  const path = corpusRelativePath.trim().replace(/^\.\//, "");
  return path.startsWith("storage/") ? `storage:${path.slice("storage/".length)}` : path;
}

export function qualifiedArtifactId(rootId: string, corpusRelativePath: string): string {
  return rootId === "default" ? corpusRelativePath : `${rootId}:${corpusRelativePath}`;
}

function basename(path: string): string {
  return path.replaceAll("\\", "/").split("/").pop() ?? "";
}

/** Repair only a basename that exactly matches an image generated by THIS host
 * run. Unmatched, remote, absolute, and already-qualified references retain
 * their author-supplied meaning. */
export function normalizeGeneratedImageLinks(body: string, generatedPaths: readonly string[]): string {
  const byName = new Map(
    generatedPaths
      .map((path) => [basename(path), markdownImageSource(path)] as const)
      .filter(([name]) => name.length > 0),
  );
  if (byName.size === 0) return body;
  return body.replace(
    /(!\[[^\]]*\]\()([^\s)]+)(\))/g,
    (whole, open: string, source: string, close: string) => {
      const replacement = byName.get(source.replace(/^\.\//, ""));
      return replacement ? `${open}${replacement}${close}` : whole;
    },
  );
}
