/**
 * The single style contract for DOCX files generated by Rotli.
 *
 * Font names are written into OOXML; Word/Pages/LibreOffice may substitute a
 * locally unavailable face. Rotli does not embed licensed font binaries.
 */
export const GENERATED_DOCX_THEME = {
  bodyFont: "Arial",
  headingFont: "Arial",
  bodyColor: "000000",
  headingColor: "000000",
  mutedColor: "000000",
  ruleColor: "C6C6C6",
  bodySizeHalfPoints: 22,
  subtitleSizeHalfPoints: 22,
  titleSizeHalfPoints: 40,
  heading1SizeHalfPoints: 32,
  heading2SizeHalfPoints: 28,
  heading3SizeHalfPoints: 24,
  pageWidthTwips: 12_240,
  pageHeightTwips: 15_840,
  marginTwips: 1_440,
} as const;
