/**
 * The single style contract for DOCX files generated by Rotli.
 *
 * Font names are written into OOXML; Word/Pages/LibreOffice may substitute a
 * locally unavailable face. Rotli does not embed licensed font binaries.
 */
export const GENERATED_DOCX_THEME = {
  bodyFont: "Aptos",
  headingFont: "Aptos Display",
  bodyColor: "262523",
  headingColor: "1B1A18",
  mutedColor: "6A665F",
  ruleColor: "CDC9C2",
  bodySizeHalfPoints: 22,
  subtitleSizeHalfPoints: 22,
  titleSizeHalfPoints: 40,
  heading1SizeHalfPoints: 32,
  heading2SizeHalfPoints: 28,
  heading3SizeHalfPoints: 24,
  pageWidthTwips: 12_240,
  pageHeightTwips: 15_840,
  marginTwips: 1_440,
} as const;
