/**
 * The single style contract for DOCX files generated by Rotli.
 *
 * Font names are written into OOXML; Word/Pages/LibreOffice may substitute a
 * locally unavailable face. Rotli does not embed licensed font binaries.
 */
export const GENERATED_DOCX_THEME = {
  bodyFont: "Arial",
  headingFont: "Arial",
  bodyColor: "000000",
  headingColor: "000000",
  mutedColor: "000000",
  ruleColor: "C6C6C6",
  tableHeaderFill: "EEEEEE",
  bodySizeHalfPoints: 24,
  subtitleSizeHalfPoints: 24,
  titleSizeHalfPoints: 48,
  heading1SizeHalfPoints: 36,
  heading2SizeHalfPoints: 30,
  heading3SizeHalfPoints: 26,
  lineSpacingTwips: 312,
  pageWidthTwips: 12_240,
  pageHeightTwips: 15_840,
  marginTwips: 1_440,
  // Univer's own drawing insertion path constrains imported images to a
  // 500×500 frame. Generated documents use the same boundary so their OOXML
  // and editor snapshots agree on geometry.
  imageMaxWidthPx: 500,
  imageMaxHeightPx: 500,
} as const;
