//! The Welcome folder: the root welcome note plus nine Markdown lessons that
//! live in the vault as ordinary notes. Vault creation and Settings → Open
//! welcome folder both seed them through `seed_welcome`, which reuses intact
//! lessons by exact title and never overwrites a user's edits: a found note is
//! refreshed to the current copy only when its body is byte-for-byte (after
//! line-ending and trailing-whitespace normalization) a body Rotli once shipped,
//! as recorded in `src/assets/welcome-history.json`. The frontend
//! files the returned ids under a `Welcome` root folder in Main; nothing here
//! touches views. `src/assets/welcome.json` is the one catalog for the welcome
//! note body (entry 0, written by the memex scaffold) and the lessons.

use std::collections::HashMap;

use serde::Serialize;
use sha2::{Digest, Sha256};

use crate::corpus::{CorpusState, CorpusStore, DEFAULT_ROOT_ID};
use crate::memex::WELCOME_PRESET_FILE;

const DIR: &str = "wiki/Welcome";
/// Physical folder for lessons in a plain (non-memex) notes folder.
const FOLDER: &str = "Welcome";

#[derive(serde::Deserialize)]
struct Entry {
    id: String,
    filename: String,
    body: String,
}

static CATALOG: std::sync::LazyLock<Vec<Entry>> = std::sync::LazyLock::new(|| {
    let entries: Vec<Entry> = serde_json::from_str(include_str!("../../src/assets/welcome.json"))
        .expect("bundled welcome catalog must be valid");
    assert_eq!(
        entries.first().map(|e| e.filename.as_str()),
        Some(WELCOME_PRESET_FILE),
        "welcome catalog must start with the root welcome note"
    );
    entries
});

/// Catalog id → SHA-256 of every body that id has shipped with. Generated by
/// `scripts/welcome-history.mjs`; `scripts/welcome-history.test.ts` fails until
/// the current welcome.json bodies are recorded.
static SHIPPED: std::sync::LazyLock<HashMap<String, Vec<String>>> = std::sync::LazyLock::new(|| {
    serde_json::from_str(include_str!("../../src/assets/welcome-history.json"))
        .expect("bundled welcome history must be valid")
});

/// Must match `welcomeBodyHash` in scripts/welcome-history.mjs.
fn body_hash(body: &str) -> String {
    let normalized = body.replace("\r\n", "\n").replace('\r', "\n");
    Sha256::digest(normalized.trim_end().as_bytes())
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

/// Bring an untouched Welcome note up to the current copy. A body the user
/// changed hashes to nothing Rotli shipped and is left exactly as it is. The
/// write goes through the store's atomic save, which keeps frontmatter, pins,
/// and the note's id.
fn refresh_if_pristine(store: &mut CorpusStore, id: &str, entry: &Entry) -> Result<(), String> {
    let shipped = SHIPPED.get(&entry.id).map(Vec::as_slice).unwrap_or_default();
    refresh_with(store, id, entry, shipped)
}

fn refresh_with(store: &mut CorpusStore, id: &str, entry: &Entry, shipped: &[String]) -> Result<(), String> {
    let on_disk = body_hash(&store.read(id)?.body);
    if on_disk != body_hash(&entry.body) && shipped.contains(&on_disk) {
        store.write(id, &entry.body)?;
    }
    Ok(())
}

/// The root welcome note's Markdown, written by `scaffold_memex`.
pub fn welcome_body() -> &'static str {
    CATALOG[0].body.as_str()
}

fn lessons() -> &'static [Entry] {
    &CATALOG[1..]
}

#[derive(Debug, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct WelcomeSeed {
    /// True when at least one lesson file was written by this call.
    pub created: bool,
    /// Stable note ids in catalog order: the root welcome note first (when it
    /// still exists), then every lesson. Main files them under one folder.
    pub note_ids: Vec<String>,
}

/** Install the lessons into the active vault as ordinary notes and return the
 * ids to file in Main. Idempotent: an intact lesson is matched by exact title
 * inside the lesson folder and reused, so user edits are never overwritten and
 * a deleted lesson comes back on the next call. The root welcome note is never
 * recreated; a vault whose owner removed it simply seeds the lessons. */
pub fn seed_welcome(store: &mut CorpusStore) -> Result<WelcomeSeed, String> {
    let folder = if store.is_memex() { DIR } else { FOLDER };
    let mut listed = store.list()?;
    let mut created = false;
    let mut note_ids = Vec::with_capacity(CATALOG.len());
    let welcome_title = crate::corpus::title_of(welcome_body());
    if let Some(welcome) = listed
        .notes
        .iter()
        .find(|note| note.title == welcome_title && note.disk_folder_id.is_empty())
    {
        note_ids.push(welcome.id.clone());
    }
    if let Some(id) = note_ids.first() {
        refresh_if_pristine(store, &id.clone(), &CATALOG[0])?;
    }
    for lesson in lessons() {
        let filename = lesson.filename.as_str();
        let body = lesson.body.as_str();
        let title = crate::corpus::title_of(body);
        let find = |list: &crate::corpus::CorpusList| {
            list.notes
                .iter()
                .find(|note| note.disk_folder_id == folder && note.title == title)
                .map(|note| note.id.clone())
        };
        let id = match find(&listed) {
            Some(id) => {
                refresh_if_pristine(store, &id, lesson)?;
                id
            }
            None => {
                // Plain Markdown files. Generic note creation adds Inbox shelf
                // metadata, which means Captures.
                store.new_file_bytes(folder, filename, body.as_bytes())?;
                created = true;
                listed = store.list()?;
                find(&listed).ok_or("seeded welcome lesson was not indexed")?
            }
        };
        note_ids.push(id);
    }
    Ok(WelcomeSeed { created, note_ids })
}

#[tauri::command]
pub fn corpus_seed_welcome(state: tauri::State<'_, CorpusState>) -> Result<WelcomeSeed, String> {
    state.route(DEFAULT_ROOT_ID, seed_welcome)
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;
    use crate::memex::scaffold_memex;

    #[test]
    fn the_catalog_is_the_welcome_note_plus_nine_lessons_with_the_promoted_grammar() {
        assert_eq!(lessons().len(), 9);
        assert!(welcome_body().starts_with("# Welcome to Rotli\n"));
        assert!(welcome_body().contains("## Guided lessons"));
        assert!(!welcome_body().contains("⌘S"));
        assert!(welcome_body()
            .contains("2. Press **⌘T** to create a note, or **⌘N** to choose what a new tab becomes."));
        let controls = &lessons()[2].body;
        assert!(controls.contains("- [#x] Medium"));
        assert!(controls.contains("- [##?] What belongs in the first release?"));
        assert!(controls.contains("- [True:green|x False:red] Ready to share"));
        assert!(controls.contains("- [:blue|:green] A color-only switch"));
        let tables = &lessons()[3].body;
        assert!(tables.starts_with("# Tables and code\n"));
        assert!(tables.contains("`[#]`"));
        for lesson in lessons() {
            assert!(!lesson.body.contains("Playground"), "{}", lesson.filename);
        }
    }

    #[test]
    fn seeding_files_the_welcome_note_first_then_stable_lesson_ids_and_restores_a_trashed_lesson() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("vault");
        scaffold_memex(&root).unwrap();
        let mut store = CorpusStore::open(root).unwrap();

        let first = seed_welcome(&mut store).unwrap();
        assert!(first.created);
        assert_eq!(first.note_ids.len(), CATALOG.len());
        assert_eq!(
            first.note_ids.iter().collect::<std::collections::HashSet<_>>().len(),
            CATALOG.len()
        );
        let listed = store.list().unwrap();
        let welcome = listed.notes.iter().find(|n| n.id == first.note_ids[0]).unwrap();
        assert_eq!(welcome.title, "Welcome to Rotli");
        assert!(welcome.disk_folder_id.is_empty());
        assert_eq!(
            listed.notes.iter().filter(|n| n.disk_folder_id == DIR).count(),
            lessons().len()
        );
        assert!(listed
            .notes
            .iter()
            .filter(|note| note.disk_folder_id == DIR)
            .all(|note| note.folder_id == DIR));
        // seeding never writes a named view; Main files the ids on the frontend
        let views = store.views_read().unwrap();
        assert!(views.trim().is_empty() || views.trim() == "{}");

        let again = seed_welcome(&mut store).unwrap();
        assert!(!again.created);
        assert_eq!(again.note_ids, first.note_ids);
        assert_eq!(store.list().unwrap().notes.len(), listed.notes.len());

        // a lesson the user moved to Trash comes back as a fresh file; the
        // others keep their ids so Main's references stay valid
        let removed = store.root().join(DIR).join(&lessons()[2].filename);
        store.delete(&first.note_ids[3]).unwrap();
        assert!(!removed.exists());
        let restored = seed_welcome(&mut store).unwrap();
        assert!(restored.created);
        assert!(removed.exists());
        assert_eq!(restored.note_ids.len(), CATALOG.len());
        for (index, id) in first.note_ids.iter().enumerate() {
            if index == 3 {
                assert_ne!(&restored.note_ids[index], id);
            } else {
                assert_eq!(&restored.note_ids[index], id);
            }
        }
    }

    #[test]
    fn seeding_reuses_an_edited_lesson_by_title_and_survives_a_removed_welcome_note() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("vault");
        scaffold_memex(&root).unwrap();
        let mut store = CorpusStore::open(root).unwrap();
        let edited = format!("{}\nMy tutorial edits.\n", lessons()[0].body);
        let rel = store
            .new_file_bytes(DIR, &lessons()[0].filename, edited.as_bytes())
            .unwrap();
        let welcome_id = store.wire_id_of(WELCOME_PRESET_FILE).unwrap();
        store.delete(&welcome_id).unwrap();
        let result = seed_welcome(&mut store).unwrap();
        assert!(result.created);
        assert_eq!(result.note_ids.len(), lessons().len());
        assert!(fs::read_to_string(store.root().join(rel))
            .unwrap()
            .contains("My tutorial edits."));
        assert_eq!(
            store
                .list()
                .unwrap()
                .notes
                .iter()
                .filter(|note| note.disk_folder_id == DIR)
                .count(),
            lessons().len()
        );
    }

    fn lesson_text(store: &mut CorpusStore, id: &str) -> String {
        store.read(id).unwrap().body
    }

    fn seeded() -> (tempfile::TempDir, CorpusStore, WelcomeSeed) {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("vault");
        scaffold_memex(&root).unwrap();
        let mut store = CorpusStore::open(root).unwrap();
        let seed = seed_welcome(&mut store).unwrap();
        (tmp, store, seed)
    }

    #[test]
    fn every_catalog_body_is_recorded_as_shipped_and_hashes_ignore_line_endings() {
        for entry in CATALOG.iter() {
            assert!(
                SHIPPED.get(&entry.id).is_some_and(|h| h.contains(&body_hash(&entry.body))),
                "run `bun scripts/welcome-history.mjs` for {}",
                entry.id
            );
        }
        assert_eq!(body_hash("# A\r\nb\n\n"), body_hash("# A\nb"));
        assert_eq!(
            body_hash(""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
    }

    #[test]
    fn a_pristine_old_lesson_is_refreshed_in_place_even_after_a_save() {
        let (_tmp, mut store, seed) = seeded();
        let entry = &lessons()[1];
        let id = seed.note_ids[2].clone();
        let old = format!("{}\nOld shipped line.\n", entry.body.trim_end());
        // raw file, exactly as an older build seeded it
        fs::write(store.root().join(DIR).join(&entry.filename), &old).unwrap();
        let shipped = vec![body_hash(&old)];
        refresh_with(&mut store, &id, entry, &shipped).unwrap();
        assert_eq!(body_hash(&lesson_text(&mut store, &id)), body_hash(&entry.body));

        // a lesson the user opened and saved unchanged is frontmatter-wrapped
        // on disk; it still reads as the shipped body and still refreshes
        store.write(&id, &old).unwrap();
        let wrapped = fs::read_dir(store.root().join(DIR))
            .unwrap()
            .filter_map(|file| fs::read_to_string(file.unwrap().path()).ok())
            .any(|text| text.starts_with("---") && text.contains("Old shipped line."));
        assert!(wrapped);
        refresh_with(&mut store, &id, entry, &shipped).unwrap();
        assert_eq!(body_hash(&lesson_text(&mut store, &id)), body_hash(&entry.body));
        assert_eq!(seed_welcome(&mut store).unwrap().note_ids, seed.note_ids);
    }

    #[test]
    fn an_edited_lesson_or_welcome_note_is_never_overwritten() {
        let (_tmp, mut store, seed) = seeded();
        let entry = &lessons()[1];
        let lesson_id = seed.note_ids[2].clone();
        let edited = format!("{}\nMy own notes.\n", entry.body.trim_end());
        store.write(&lesson_id, &edited).unwrap();
        let welcome_id = seed.note_ids[0].clone();
        let welcome = format!("{}\nMine now.\n", welcome_body().trim_end());
        store.write(&welcome_id, &welcome).unwrap();

        let again = seed_welcome(&mut store).unwrap();
        assert!(!again.created);
        assert_eq!(again.note_ids, seed.note_ids);
        assert!(lesson_text(&mut store, &lesson_id).contains("My own notes."));
        assert!(lesson_text(&mut store, &welcome_id).contains("Mine now."));
        // a current, untouched lesson is not rewritten (no churn on every open)
        let other = seed.note_ids[3].clone();
        let before = fs::read_to_string(store.root().join(DIR).join(&lessons()[2].filename)).unwrap();
        seed_welcome(&mut store).unwrap();
        assert_eq!(
            fs::read_to_string(store.root().join(DIR).join(&lessons()[2].filename)).unwrap(),
            before
        );
        assert!(!lesson_text(&mut store, &other).is_empty());
    }
}
